In [ ]:
import pandas as pd
import sqlite3

# Load dataset directly from GitHub
url = "https://raw.githubusercontent.com/sarthaksingh3007-crypto/Uber-data-analysis/main/cleaned%20data%20uber.xlsx"

df = pd.read_excel(url)

print("✅ Dataset loaded successfully!")
print("Shape:", df.shape)

# Create SQLite database locally
conn = sqlite3.connect('uber.db')

# Create table
df.to_sql('trips', conn, if_exists='replace', index=False)

print("✅ SQL database created successfully!")

# Preview data
df.head()

✅ Dataset loaded successfully!
Shape: (6745, 12)
✅ SQL database created successfully!

/tmp/ipykernel_6254/3628315470.py:16: UserWarning: the 'timedelta' type is not supported, and will be written as integer values (ns frequency) to the database.
  df.to_sql('trips', conn, if_exists='replace', index=False)

,Request id,Duplicate Check,Pickup point,Driver id,Status,Request timestamp,Request Hour,Time Slot,Drop timestamp,Ride Duration,Pickup Point Clean,Pickup Point Proper
0,619,1,Airport,1.0,Trip Completed,2016-07-11 11:51:00,11,Afternoon,2016-07-11 13:00:00,0 days 01:09:00,Airport,Airport
1,867,1,Airport,1.0,Trip Completed,2016-07-11 17:57:00,17,Evening,2016-07-11 18:47:00,0 days 00:50:00,Airport,Airport
2,1807,1,City,1.0,Trip Completed,2016-07-12 09:17:00,9,Early Morning,2016-07-12 09:58:00,0 days 00:41:00,City,City
3,2532,1,Airport,1.0,Trip Completed,2016-07-12 21:08:00,21,Night,2016-07-12 22:03:00,0 days 00:55:00,Airport,Airport
4,3112,1,City,1.0,Trip Completed,2016-07-13 08:33:16,8,Early Morning,2016-07-13 09:25:47,0 days 00:52:31,City,City

In [ ]:
import pandas as pd
import sqlite3

url = "https://raw.githubusercontent.com/sarthaksingh3007-crypto/Uber-data-analysis/main/cleaned%20data%20uber.xlsx"

df = pd.read_excel(url)

print("✅ Dataset loaded successfully!")
print("Shape:", df.shape)

conn = sqlite3.connect('uber.db')
df.to_sql('trips', conn, if_exists='replace', index=False)

print("✅ SQL database created successfully!")

df.head()

✅ Dataset loaded successfully!
Shape: (6745, 12)
✅ SQL database created successfully!

/tmp/ipykernel_6254/3872647336.py:12: UserWarning: the 'timedelta' type is not supported, and will be written as integer values (ns frequency) to the database.
  df.to_sql('trips', conn, if_exists='replace', index=False)

,Request id,Duplicate Check,Pickup point,Driver id,Status,Request timestamp,Request Hour,Time Slot,Drop timestamp,Ride Duration,Pickup Point Clean,Pickup Point Proper
0,619,1,Airport,1.0,Trip Completed,2016-07-11 11:51:00,11,Afternoon,2016-07-11 13:00:00,0 days 01:09:00,Airport,Airport
1,867,1,Airport,1.0,Trip Completed,2016-07-11 17:57:00,17,Evening,2016-07-11 18:47:00,0 days 00:50:00,Airport,Airport
2,1807,1,City,1.0,Trip Completed,2016-07-12 09:17:00,9,Early Morning,2016-07-12 09:58:00,0 days 00:41:00,City,City
3,2532,1,Airport,1.0,Trip Completed,2016-07-12 21:08:00,21,Night,2016-07-12 22:03:00,0 days 00:55:00,Airport,Airport
4,3112,1,City,1.0,Trip Completed,2016-07-13 08:33:16,8,Early Morning,2016-07-13 09:25:47,0 days 00:52:31,City,City

In [ ]:
print(df.columns.tolist())

['Request id', 'Duplicate Check', 'Pickup point', 'Driver id', 'Status', 'Request timestamp', 'Request Hour', 'Time Slot', 'Drop timestamp', 'Ride Duration', 'Pickup Point Clean', 'Pickup Point Proper']

In [ ]:
# Clean column names
df.columns = df.columns.str.strip().str.replace(' ', '_')

# Create SQLite database
conn = sqlite3.connect('uber.db')
df.to_sql('trips', conn, if_exists='replace', index=False)

print("✅ Database ready! Table 'trips' created.")

/tmp/ipykernel_6254/3650816323.py:6: UserWarning: the 'timedelta' type is not supported, and will be written as integer values (ns frequency) to the database.
  df.to_sql('trips', conn, if_exists='replace', index=False)

✅ Database ready! Table 'trips' created.

In [ ]:
# Clean column names (removes spaces)
df.columns = df.columns.str.strip().str.replace(' ', '_')

# Create SQLite database
conn = sqlite3.connect('uber.db')
df.to_sql('trips', conn, if_exists='replace', index=False)

print("✅ Database ready! Table 'trips' created.")

/tmp/ipykernel_6254/4095922777.py:6: UserWarning: the 'timedelta' type is not supported, and will be written as integer values (ns frequency) to the database.
  df.to_sql('trips', conn, if_exists='replace', index=False)

✅ Database ready! Table 'trips' created.

In [ ]:
print("Database created successfully!")

Database created successfully!

In [ ]:
def run_query(sql, title=""):
    result = pd.read_sql_query(sql, conn)
    if title:
        print(f"\n{'='*50}")
        print(f"  {title}")
        print(f"{'='*50}")
    display(result)
    return result

In [ ]:
import pandas as pd
import sqlite3

conn = sqlite3.connect('uber.db')

query = """
SELECT
    Status,
    COUNT(*) AS Total_Trips
FROM trips
GROUP BY Status
ORDER BY Total_Trips DESC
"""

result = pd.read_sql_query(query, conn)

print("📊 Trip Count by Status")
print(result)

📊 Trip Count by Status
              Status  Total_Trips
0     Trip Completed         2831
1  No Cars Available         2650
2          Cancelled         1264

In [ ]:
def run_query(sql, title="Results"):
    import pandas as pd

    result = pd.read_sql_query(sql, conn)

    print("\n" + "="*50)
    print(title)
    print("="*50)

    print(result.to_string(index=False))

    return result

In [ ]:
run_query("""
SELECT
    Status,
    COUNT(*) AS Total_Trips
FROM trips
GROUP BY Status
ORDER BY Total_Trips DESC
""", title="Query 1 - Trip Count by Status")

==================================================
Query 1 - Trip Count by Status
==================================================
           Status  Total_Trips
   Trip Completed         2831
No Cars Available         2650
        Cancelled         1264

              Status  Total_Trips
0     Trip Completed         2831
1  No Cars Available         2650
2          Cancelled         1264

In [ ]:
print(pd.read_sql_query("PRAGMA table_info(trips);", conn))

    cid                 name       type  notnull dflt_value  pk
0     0           Request_id    INTEGER        0       None   0
1     1      Duplicate_Check    INTEGER        0       None   0
2     2         Pickup_point       TEXT        0       None   0
3     3            Driver_id       REAL        0       None   0
4     4               Status       TEXT        0       None   0
5     5    Request_timestamp  TIMESTAMP        0       None   0
6     6         Request_Hour    INTEGER        0       None   0
7     7            Time_Slot       TEXT        0       None   0
8     8       Drop_timestamp  TIMESTAMP        0       None   0
9     9        Ride_Duration    INTEGER        0       None   0
10   10   Pickup_Point_Clean       TEXT        0       None   0
11   11  Pickup_Point_Proper       TEXT        0       None   0

In [ ]:
run_query("""
SELECT
    Request_Hour,
    COUNT(*) AS Unfulfilled_Requests
FROM trips
WHERE Status IN ('Cancelled', 'No Cars Available')
GROUP BY Request_Hour
ORDER BY Request_Hour
""", title="Query 2 - Unfulfilled Requests Per Hour")

==================================================
Query 2 - Unfulfilled Requests Per Hour
==================================================
 Request_Hour  Unfulfilled_Requests
            0                    59
            1                    60
            2                    62
            3                    58
            4                   125
            5                   260
            6                   231
            7                   232
            8                   268
            9                   258
           10                   127
           11                    56
           12                    63
           13                    71
           14                    48
           15                    69
           16                    68
           17                   267
           18                   346
           19                   307
           20                   331
           21                   307
           22                   150
           23                    91

    Request_Hour  Unfulfilled_Requests
0              0                    59
1              1                    60
2              2                    62
3              3                    58
4              4                   125
5              5                   260
6              6                   231
7              7                   232
8              8                   268
9              9                   258
10            10                   127
11            11                    56
12            12                    63
13            13                    71
14            14                    48
15            15                    69
16            16                    68
17            17                   267
18            18                   346
19            19                   307
20            20                   331
21            21                   307
22            22                   150
23            23                    91

In [ ]:
run_query("""
SELECT
    Time_Slot,
    COUNT(*) AS Unfulfilled_Requests
FROM trips
WHERE Status IN ('Cancelled', 'No Cars Available')
GROUP BY Time_Slot
ORDER BY Unfulfilled_Requests DESC
""", title="Query 3 - Supply Demand Gap by Time of Day")

==================================================
Query 3 - Supply Demand Gap by Time of Day
==================================================
    Time_Slot  Unfulfilled_Requests
      Evening                  1251
Early Morning                  1249
        Night                   548
    Afternoon                   502
   Late Night                   364

       Time_Slot  Unfulfilled_Requests
0        Evening                  1251
1  Early Morning                  1249
2          Night                   548
3      Afternoon                   502
4     Late Night                   364

In [ ]:
run_query("""
SELECT
    Pickup_Point_Proper,
    Status,
    COUNT(*) AS Total_Requests
FROM trips
WHERE Status IN ('Cancelled', 'No Cars Available')
GROUP BY Pickup_Point_Proper, Status
ORDER BY Pickup_Point_Proper, Total_Requests DESC
""", title="Query 4 - Airport vs City Cancelled and No Cars")

==================================================
Query 4 - Airport vs City Cancelled and No Cars
==================================================
Pickup_Point_Proper            Status  Total_Requests
            Airport No Cars Available            1713
            Airport         Cancelled             198
               City         Cancelled            1066
               City No Cars Available             937

  Pickup_Point_Proper             Status  Total_Requests
0             Airport  No Cars Available            1713
1             Airport          Cancelled             198
2                City          Cancelled            1066
3                City  No Cars Available             937

In [ ]:
run_query("""
SELECT
    Driver_id,
    COUNT(*) AS Cancellations
FROM trips
WHERE Status = 'Cancelled'
    AND Driver_id IS NOT NULL
    AND Driver_id <> ''
GROUP BY Driver_id
ORDER BY Cancellations DESC
LIMIT 10
""", title="Query 5 - Top 10 Drivers by Cancellations")

==================================================
Query 5 - Top 10 Drivers by Cancellations
==================================================
 Driver_id  Cancellations
      84.0             12
      54.0             11
     206.0             10
     142.0             10
     267.0              9
     210.0              9
     166.0              9
     138.0              9
     114.0              9
      27.0              9

   Driver_id  Cancellations
0       84.0             12
1       54.0             11
2      206.0             10
3      142.0             10
4      267.0              9
5      210.0              9
6      166.0              9
7      138.0              9
8      114.0              9
9       27.0              9

In [ ]:
run_query("""
SELECT
    Pickup_point,
    COUNT(*) AS Total_Requests,
    SUM(CASE WHEN Status = 'Trip Completed' THEN 1 ELSE 0 END) AS Completed,
    ROUND(
        100.0 * SUM(CASE WHEN Status = 'Trip Completed' THEN 1 ELSE 0 END)
        / COUNT(*),
        1
    ) AS Completion_Rate_Pct
FROM trips
GROUP BY Pickup_point
ORDER BY Completion_Rate_Pct DESC
""", title="Query 6 - Completion Rate Airport vs City")

==================================================
Query 6 - Completion Rate Airport vs City
==================================================
Pickup_point  Total_Requests  Completed  Completion_Rate_Pct
        City            3507       1504                 42.9
     Airport            3238       1327                 41.0

  Pickup_point  Total_Requests  Completed  Completion_Rate_Pct
0         City            3507       1504                 42.9
1      Airport            3238       1327                 41.0

In [ ]:
run_query("""
SELECT
    Pickup_point,
    Time_Slot,
    COUNT(*) AS Problem_Requests
FROM trips
WHERE Status IN ('Cancelled', 'No Cars Available')
GROUP BY Pickup_point, Time_Slot
ORDER BY Problem_Requests DESC
LIMIT 10
""", title="Query 7 - Worst Pickup Point and Time Slot Combos")

==================================================
Query 7 - Worst Pickup Point and Time Slot Combos
==================================================
Pickup_point     Time_Slot  Problem_Requests
        City Early Morning              1205
     Airport       Evening              1145
     Airport         Night               421
        City     Afternoon               351
        City    Late Night               214
     Airport     Afternoon               151
     Airport    Late Night               150
        City         Night               127
        City       Evening               106
     Airport Early Morning                44

  Pickup_point      Time_Slot  Problem_Requests
0         City  Early Morning              1205
1      Airport        Evening              1145
2      Airport          Night               421
3         City      Afternoon               351
4         City     Late Night               214
5      Airport      Afternoon               151
6      Airport     Late Night               150
7         City          Night               127
8         City        Evening               106
9      Airport  Early Morning                44